/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:852f1146-25cd-4a83-a756-5f5091fdb53b",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_vzht8iuBl",
    "aws_user_pools_web_client_id": "voq51uncia50sa2kp24k5dchj",
    "oauth": {},
    "aws_user_files_s3_bucket": "images101203-develop",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "bgremove",
            "endpoint": "https://qlhdx591bc.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "cdnInvalidator",
            "endpoint": "https://lwlv11qa4m.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "stripeWebHooks",
            "endpoint": "https://2ljn7no4t6.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "stripeCheckout",
            "endpoint": "https://wrk2h1t5nb.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "creditsCalculation",
            "endpoint": "https://t8psjsc452.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "getCredits",
            "endpoint": "https://lb6gqopypa.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "signsUpFreeCredits",
            "endpoint": "https://1c0xf5cff0.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "gallerySelfieCounts",
            "endpoint": "https://85dksu4ptc.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "exportSelfies",
            "endpoint": "https://wy42rbgucj.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "downloadAllSelfie",
            "endpoint": "https://w6dw8nmff6.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "getStripeSession",
            "endpoint": "https://d4brsiqby9.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "getStripeCustomerDetails",
            "endpoint": "https://67ppmbjtc9.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "updateStripeCustomerDetails",
            "endpoint": "https://8rf4fmrxk1.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        },
        {
            "name": "getCustomerInvoices",
            "endpoint": "https://mlqqh7zk2f.execute-api.eu-central-1.amazonaws.com/develop",
            "region": "eu-central-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://f7s6k6sswra57ijxgnxpskhuwi.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ipqnvz4a4bhqhfjtxlxa5gzk3m"
};
